== How to use this service

==== How do I sign up?

  curl -i -H "Content-Type: application/json" -X POST -d '{
      "username": "admin",
      "password": "password",
      "email": "admin@example.com"
  }' http://localhost:8080/UAAService/signup

You will receive a JWT as output.

==== How do I log in?

  curl -i -H "Content-Type: application/json" -X POST -d '{
      "username": "max",
      "password": "password"
  }' http://localhost:8080/UAAService/login
  
You will receive a JWT as output.

==== How do I validate the JWT?

    curl -i -H "Authorization: Bearer xxx.yyy.zzz" -X GET http://localhost:8080/UAAService/validate

==== How do I get user information from the JWT?

    curl -i -H "Authorization: Bearer xxx.yyy.zzz" -X GET http://localhost:8080/UAAService/resolve

==== How do I update a user?

  curl -i -H "Authorization: Bearer xxx.yyy.zzz" -H "Content-Type: application/json" -X PUT -d '{
      "username": "admin",
      "password": "password",
      "email": "namid@example.com"
  }' http://localhost:8080/UAAService/admin

==== How do I delete a user?

    curl -i -H "Authorization: Bearer xxx.yyy.zzz" -X DELETE localhost:8080/UAAService/{username}

==== How do I check the health status?

    localhost:8080/UAAService/health

==== How do I get access to the api documentation?

    localhost:8080/UAAService/swagger-ui.html